import {
  Activity,
  Award,
  BookOpen,
  Bot,
  Boxes,
  Brain,
  Briefcase,
  Bug,
  CodeXml,
  Cpu,
  Database,
  FileText,
  GitPullRequest,
  GraduationCap,
  Layers,
  LayoutTemplate,
  Lightbulb,
  Network,
  Puzzle,
  Rocket,
  ScanSearch,
  Server,
  ShieldCheck,
  Sparkles,
  Terminal,
  Trophy,
  Workflow,
  Wrench,
  type LucideIcon,
} from "lucide-react";

/**
 * Icons referenced by name from the content files in `src/data`.
 * Add an entry here to make a new icon available to the data files.
 */
export const icons = {
  activity: Activity,
  award: Award,
  book: BookOpen,
  bot: Bot,
  boxes: Boxes,
  brain: Brain,
  briefcase: Briefcase,
  bug: Bug,
  code: CodeXml,
  cpu: Cpu,
  database: Database,
  "file-text": FileText,
  "git-pull-request": GitPullRequest,
  "graduation-cap": GraduationCap,
  layers: Layers,
  layout: LayoutTemplate,
  lightbulb: Lightbulb,
  network: Network,
  puzzle: Puzzle,
  rocket: Rocket,
  scan: ScanSearch,
  server: Server,
  shield: ShieldCheck,
  sparkles: Sparkles,
  terminal: Terminal,
  trophy: Trophy,
  workflow: Workflow,
  wrench: Wrench,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;
